.TH "AudioComponent" 3 "Aguados Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AudioComponent \- Struct representing an audio component attached to an entity\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <default_components\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAudioComponent\fP (\fBSoundBuffer\fP &buff, std::string name, ALfloat pos[3], ALfloat speed[3], float gain=1\&.0f, float pitch=1\&.0f, bool play=false)"
.br
.RI "Constructor that creates an \fBAudioComponent\fP with a sound source and optionally plays it\&. "
.ti -1c
.RI "\fBAudioComponent\fP ()=default"
.br
.RI "Default constructor that initializes an empty \fBAudioComponent\fP\&. "
.ti -1c
.RI "\fBAudioComponent\fP & \fBoperator=\fP (const \fBAudioComponent\fP &o)=default"
.br
.RI "Copy assignment operator (default behavior is sufficient)\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSoundSource\fP \fBsound_source_\fP"
.br
.RI "Internal sound source object used for audio playback\&. "
.in -1c
.SH "Detailed Description"
.PP 
Struct representing an audio component attached to an entity\&. 

This struct manages a sound source object and allows attaching a sound buffer to it for playback\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AudioComponent::AudioComponent (\fBSoundBuffer\fP & buff, std::string name, ALfloat pos[3], ALfloat speed[3], float gain = \fR1\&.0f\fP, float pitch = \fR1\&.0f\fP, bool play = \fRfalse\fP)\fR [inline]\fP"

.PP
Constructor that creates an \fBAudioComponent\fP with a sound source and optionally plays it\&. This constructor takes various arguments to initialize the sound source: 
.PP
\fBParameters\fP
.RS 4
\fIbuff\fP Reference to a \fR\fBSoundBuffer\fP\fP object containing the audio data\&. 
.br
\fIname\fP A name for the sound source (for debugging purposes)\&. 
.br
\fIpos\fP Position of the sound source in 3D space (ALfloat array of length 3)\&. 
.br
\fIspeed\fP Velocity of the sound source (ALfloat array of length 3)\&. 
.br
\fIgain\fP Gain of the sound source (volume amplification)\&. Defaults to 1\&.0f\&. 
.br
\fIpitch\fP Pitch of the sound source (alters playback speed)\&. Defaults to 1\&.0f\&. 
.br
\fIplay\fP If true, starts playing the sound after creation\&. Defaults to false\&.
.RE
.PP
After setting up the sound source, it adds the provided sound buffer using the \fRaddSound\fP function and optionally starts playback using the \fRPlay\fP function\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Aguados Engine from the source code\&.
