.TH "BoxColliderComponent" 3 "Aguados Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BoxColliderComponent \- Struct representing a box collider attached to an entity\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <default_components\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBoxColliderComponent\fP ()=default"
.br
.RI "Default constructor that initializes the box collider with zero extent and no offset\&. "
.ti -1c
.RI "\fBBoxColliderComponent\fP (\fBVec3\fP extent, \fBVec3\fP center_offset=\fBVec3\fP(0\&.0f, 0\&.0f, 0\&.0f))"
.br
.RI "Constructor that initializes the extent and center offset of the box collider\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVec3\fP \fBextent_\fP"
.br
.RI "Half-extents of the box collider along each axis (X, Y, Z)\&. "
.ti -1c
.RI "\fBVec3\fP \fBcenter_offset_\fP"
.br
.RI "Offset of the bounding box from the entity's center\&. "
.in -1c
.SH "Detailed Description"
.PP 
Struct representing a box collider attached to an entity\&. 

This struct defines a bounding box for collision detection purposes\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BoxColliderComponent::BoxColliderComponent (\fBVec3\fP extent, \fBVec3\fP center_offset = \fR\fBVec3\fP(0\&.0f, 0\&.0f, 0\&.0f)\fP)"

.PP
Constructor that initializes the extent and center offset of the box collider\&. 
.PP
\fBParameters\fP
.RS 4
\fIextent\fP Half-extents of the box collider along each axis (X, Y, Z)\&. 
.br
\fIcenter_offset\fP Offset of the bounding box from the entity's center\&. Defaults to (0, 0, 0)\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Aguados Engine from the source code\&.
