.TH "Buffers" 3 "Aguados Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Buffers \- Vertex and Index Buffers
.PP
 \- This file defines classes for managing vertex and index buffers in OpenGL\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBVertexBuffer\fP"
.br
.RI "This class represents a vertex buffer object (VBO) in OpenGL\&. "
.ti -1c
.RI "class \fBIndexBuffer\fP"
.br
.RI "This class represents an index buffer object (IBO) in OpenGL\&. "
.in -1c
.SH "Detailed Description"
.PP 
This file defines classes for managing vertex and index buffers in OpenGL\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Aguados Engine from the source code\&.
