.TH "C:/Users/lermami/Documents/3MG_TA_lermami_fuertesco/include/buffer.hpp" 3 "Aguados Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/lermami/Documents/3MG_TA_lermami_fuertesco/include/buffer.hpp \- Header file for the \fBVertexBuffer\fP and \fBIndexBuffer\fP classes\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <memory>\fP
.br
\fR#include 'enum\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBVertexBuffer\fP"
.br
.RI "This class represents a vertex buffer object (VBO) in OpenGL\&. "
.ti -1c
.RI "class \fBIndexBuffer\fP"
.br
.RI "This class represents an index buffer object (IBO) in OpenGL\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header file for the \fBVertexBuffer\fP and \fBIndexBuffer\fP classes\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Aguados Engine from the source code\&.
