.TH "ColorComponent" 3 "Aguados Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ColorComponent \- Struct representing an entity's color information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <default_components\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColorComponent\fP ()=default"
.br
.RI "Default constructor that initializes the color to black (0, 0, 0, 1)\&. "
.ti -1c
.RI "\fBColorComponent\fP (\fBVec4\fP color)"
.br
.RI "Constructor that initializes the color of the entity\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVec4\fP \fBcolor_\fP"
.br
.RI "RGBA color of the entity\&. "
.in -1c
.SH "Detailed Description"
.PP 
Struct representing an entity's color information\&. 

This struct stores the RGBA color of an entity\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ColorComponent::ColorComponent (\fBVec4\fP color)"

.PP
Constructor that initializes the color of the entity\&. 
.PP
\fBParameters\fP
.RS 4
\fIcolor\fP The RGBA color of the entity\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Aguados Engine from the source code\&.
