.TH "defaul_systems" 3 "Aguados Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
defaul_systems \- defaul_systems
.PP
 \- This file defines the defaul systems of entities\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
This file defines the defaul systems of entities\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Aguados Engine from the source code\&.
