.TH "defaul_components" 3 "Aguados Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
defaul_components \- defaul_components
.PP
 \- This file defines the defaul components of entities\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
This file defines the defaul components of entities\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Aguados Engine from the source code\&.
