.TH "C:/Users/lermami/Documents/3MG_TA_lermami_fuertesco/include/Engine.hpp" 3 "Aguados Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/lermami/Documents/3MG_TA_lermami_fuertesco/include/Engine.hpp \- Header file for the \fBEngine\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <vector>\fP
.br
\fR#include <memory>\fP
.br
\fR#include 'enum\&.hpp'\fP
.br
\fR#include 'resource_manager\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEngine\fP"
.br
.RI "Main class representing the game engine, managing core subsystems\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header file for the \fBEngine\fP class\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Aguados Engine from the source code\&.
