.TH "EntityManager" 3 "Aguados Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EntityManager \- Entity Manager
.PP
 \- This file defines the \fBComponentManager\fP class, which manages the components attached to entities in the game world\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBComponentManager\fP"
.br
.RI "This class manages the components attached to entities in the game world\&. "
.in -1c
.SH "Detailed Description"
.PP 
This file defines the \fBComponentManager\fP class, which manages the components attached to entities in the game world\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Aguados Engine from the source code\&.
