.TH "Geometry" 3 "Aguados Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Geometry \- Struct representing geometric data for rendering\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <default_components\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBVertex\fP > \fBvertex_\fP"
.br
.RI "List of vertices that define the geometry\&. "
.ti -1c
.RI "std::vector< unsigned > \fBindices_\fP"
.br
.RI "List of indices that specify the order of vertices to form triangles\&. "
.in -1c
.SH "Detailed Description"
.PP 
Struct representing geometric data for rendering\&. 

This struct holds a collection of vertices and indices used to define the mesh of a 3D object\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Aguados Engine from the source code\&.
