.TH "C:/Users/lermami/Documents/3MG_TA_lermami_fuertesco/include/input.hpp" 3 "Aguados Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/lermami/Documents/3MG_TA_lermami_fuertesco/include/input.hpp \- Header file for the \fBKey\fP and \fBInput\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'GLFW/glfw3\&.h'\fP
.br
\fR#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBKey\fP"
.br
.RI "Represents a key and its input state\&. "
.ti -1c
.RI "class \fBInput\fP"
.br
.RI "Manages input for the application, including keyboard, mouse, and scroll events\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header file for the \fBKey\fP and \fBInput\fP class\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Aguados Engine from the source code\&.
