.TH "LightComponent" 3 "Aguados Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LightComponent
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLightComponent\fP ()"
.br
.RI "Default constructor for \fBLightComponent\fP\&. Sets all member variables to default values\&. "
.ti -1c
.RI "\fBLightComponent\fP (\fBVec3\fP color)"
.br
.RI "Constructor for \fBLightComponent\fP to init an Ambient Light\&. "
.ti -1c
.RI "\fBLightComponent\fP (\fBVec3\fP direction, \fBVec3\fP color, \fBVec3\fP specular, float min_shadow_render_distance=0\&.01f, float max_shadow_render_distance=1000)"
.br
.RI "Constructor for \fBLightComponent\fP to init a Directional Light\&. "
.ti -1c
.RI "\fBLightComponent\fP (\fBVec3\fP color, \fBVec3\fP specular, float constant, float linear, float quadratic, float min_shadow_render_distance=0\&.01f, float max_shadow_render_distance=1000)"
.br
.RI "Constructor for \fBLightComponent\fP to init a point light\&. "
.ti -1c
.RI "\fBLightComponent\fP (\fBVec3\fP direction, \fBVec3\fP color, \fBVec3\fP specular, float constant, float linear, float quadratic, float cutoff_angle, float min_shadow_render_distance=0\&.01f, float max_shadow_render_distance=1000)"
.br
.RI "Constructor for \fBLightComponent\fP to init a spot light\&. "
.ti -1c
.RI "\fB~LightComponent\fP ()"
.br
.RI "Destructor for \fBLightComponent\fP\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "LightType \fBtype_\fP"
.br
.RI "The type of the light (ambient, directional, point, or spot)\&. "
.ti -1c
.RI "\fBVec3\fP \fBcolor_\fP"
.br
.RI "The color of the light\&. "
.ti -1c
.RI "\fBVec3\fP \fBspec_color_\fP"
.br
.RI "The specular color of the light (used for specular lighting calculations)\&. "
.ti -1c
.RI "\fBVec3\fP \fBdirection_\fP"
.br
.RI "The direction of the light (only relevant for directional and spot lights)\&. "
.ti -1c
.RI "float \fBconstant_\fP"
.br
.RI "The constant attenuation factor of the light (used for distance-based attenuation) (Not used for ambient lights) "
.ti -1c
.RI "float \fBlinear_\fP"
.br
.RI "The linear attenuation factor of the light (used for distance-based attenuation) (Not used for ambient lights) "
.ti -1c
.RI "float \fBquadratic_\fP"
.br
.RI "The quadratic attenuation factor of the light (used for distance-based attenuation) (Not used for ambient lights) "
.ti -1c
.RI "float \fBcutoff_angle_\fP"
.br
.RI "The cutoff angle of the spot light (in radians) (only relevant for spot lights)\&. "
.ti -1c
.RI "float \fBmin_shadow_render_distance_\fP"
.br
.RI "The minimum distance at which shadows are rendered for this light\&. (Not used for ambient lights) "
.ti -1c
.RI "float \fBmax_shadow_render_distance_\fP"
.br
.RI "The maximum distance at which shadows are rendered for this light\&. (Not used for ambient lights) "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LightComponent::LightComponent (\fBVec3\fP color)"

.PP
Constructor for \fBLightComponent\fP to init an Ambient Light\&. Initializes the light with the provided color and sets other member variables to defaults\&.
.PP
\fBParameters\fP
.RS 4
\fIcolor\fP The color of the light\&. 
.RE
.PP

.SS "LightComponent::LightComponent (\fBVec3\fP direction, \fBVec3\fP color, \fBVec3\fP specular, float min_shadow_render_distance = \fR0\&.01f\fP, float max_shadow_render_distance = \fR1000\fP)"

.PP
Constructor for \fBLightComponent\fP to init a Directional Light\&. Initializes the light as a directional light with the provided direction, color, specular color, minimum and maximum shadow rendering distances\&.
.PP
\fBParameters\fP
.RS 4
\fIdirection\fP The direction of the light\&. 
.br
\fIcolor\fP The color of the light\&. 
.br
\fIspecular\fP The specular color of the light\&. 
.br
\fImin_shadow_render_distance\fP The minimum distance for shadow rendering\&. 
.br
\fImax_shadow_render_distance\fP The maximum distance for shadow rendering\&. 
.RE
.PP

.SS "LightComponent::LightComponent (\fBVec3\fP color, \fBVec3\fP specular, float constant, float linear, float quadratic, float min_shadow_render_distance = \fR0\&.01f\fP, float max_shadow_render_distance = \fR1000\fP)"

.PP
Constructor for \fBLightComponent\fP to init a point light\&. Initializes the light as a point light with the provided color, specular color, constant, linear, and quadratic attenuation factors, minimum and maximum shadow rendering distances\&.
.PP
\fBParameters\fP
.RS 4
\fIcolor\fP The color of the light\&. 
.br
\fIspecular\fP The specular color of the light\&. 
.br
\fIconstant\fP The constant attenuation factor\&. 
.br
\fIlinear\fP The linear attenuation factor\&. 
.br
\fIquadratic\fP The quadratic attenuation factor\&. 
.br
\fImin_shadow_render_distance\fP The minimum distance for shadow rendering\&. 
.br
\fImax_shadow_render_distance\fP The maximum distance for shadow rendering\&. 
.RE
.PP

.SS "LightComponent::LightComponent (\fBVec3\fP direction, \fBVec3\fP color, \fBVec3\fP specular, float constant, float linear, float quadratic, float cutoff_angle, float min_shadow_render_distance = \fR0\&.01f\fP, float max_shadow_render_distance = \fR1000\fP)"

.PP
Constructor for \fBLightComponent\fP to init a spot light\&. Initializes the light as a spot light with the provided direction, color, specular color, constant, linear, and quadratic attenuation factors, cutoff angle, minimum and maximum shadow rendering distances\&.
.PP
\fBParameters\fP
.RS 4
\fIdirection\fP The direction of the light\&. 
.br
\fIcolor\fP The color of the light\&. 
.br
\fIspecular\fP The specular color of the light\&. 
.br
\fIconstant\fP The constant attenuation factor\&. 
.br
\fIlinear\fP The linear attenuation factor\&. 
.br
\fIquadratic\fP The quadratic attenuation factor\&. 
.br
\fIcutoff_angle\fP The cutoff angle of the spot light (in radians)\&. 
.br
\fImin_shadow_render_distance\fP The minimum distance for shadow rendering\&. 
.br
\fImax_shadow_render_distance\fP The maximum distance for shadow rendering\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Aguados Engine from the source code\&.
