.TH "Mat4" 3 "Aguados Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mat4
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMat4\fP (float a[16])"
.br
.ti -1c
.RI "\fBMat4\fP (float value)"
.br
.ti -1c
.RI "\fBMat4\fP (const \fBMat4\fP &copy)"
.br
.ti -1c
.RI "\fBMat4\fP \fBMultiply\fP (const \fBMat4\fP &other) const"
.br
.ti -1c
.RI "float \fBDeterminant\fP () const"
.br
.ti -1c
.RI "\fBMat4\fP \fBAdjoint\fP () const"
.br
.ti -1c
.RI "bool \fBGetInverse\fP (\fBMat4\fP *out) const"
.br
.ti -1c
.RI "bool \fBInverse\fP ()"
.br
.ti -1c
.RI "\fBMat4\fP \fBTranspose\fP () const"
.br
.ti -1c
.RI "\fBMat4\fP \fBGetTransform\fP (const \fBVec3\fP &translate, const \fBVec3\fP &scale, float rotateX, float rotateY, float rotateZ)"
.br
.ti -1c
.RI "\fBVec4\fP \fBTransform_Mat4_Vec4\fP (\fBMat4\fP mat, \fBVec4\fP vec)"
.br
.ti -1c
.RI "\fBVec3\fP \fBTransform_Mat4_Vec3\fP (\fBMat4\fP mat, \fBVec3\fP vec)"
.br
.ti -1c
.RI "\fBMat4\fP \fBPerspectiveMatrix\fP (float fov, float aspect, float near, float far) const"
.br
.ti -1c
.RI "\fBMat4\fP \fBOrthoMatrix\fP (float right, float left, float top, float valueottom, float near, float far) const"
.br
.ti -1c
.RI "\fBVec4\fP \fBGetColum\fP (int colum) const"
.br
.ti -1c
.RI "\fBVec4\fP \fBGetLine\fP (int line) const"
.br
.ti -1c
.RI "\fBMat4\fP \fBoperator+\fP (const \fBMat4\fP &other) const"
.br
.ti -1c
.RI "\fBMat4\fP & \fBoperator+=\fP (const \fBMat4\fP &other)"
.br
.ti -1c
.RI "\fBMat4\fP \fBoperator+\fP (float value) const"
.br
.ti -1c
.RI "\fBMat4\fP & \fBoperator+=\fP (float value)"
.br
.ti -1c
.RI "\fBMat4\fP \fBoperator\-\fP (const \fBMat4\fP &other) const"
.br
.ti -1c
.RI "\fBMat4\fP & \fBoperator\-=\fP (const \fBMat4\fP &other)"
.br
.ti -1c
.RI "\fBMat4\fP \fBoperator\-\fP (float value) const"
.br
.ti -1c
.RI "\fBMat4\fP & \fBoperator\-=\fP (float value)"
.br
.ti -1c
.RI "\fBMat4\fP & \fBoperator*=\fP (float value)"
.br
.ti -1c
.RI "\fBMat4\fP \fBoperator*\fP (float value) const"
.br
.ti -1c
.RI "\fBMat4\fP & \fBoperator/=\fP (float value)"
.br
.ti -1c
.RI "\fBMat4\fP \fBoperator/\fP (float value) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBMat4\fP &other)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBMat4\fP &other)"
.br
.ti -1c
.RI "void \fBoperator=\fP (const \fBMat4\fP &other)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBMat4\fP \fBIdentity\fP ()"
.br
.ti -1c
.RI "static \fBMat4\fP \fBTranslate\fP (const \fBVec3\fP &distance)"
.br
.ti -1c
.RI "static \fBMat4\fP \fBTranslate\fP (float x, float y, float z)"
.br
.ti -1c
.RI "static \fBMat4\fP \fBScale\fP (const \fBVec3\fP &scale)"
.br
.ti -1c
.RI "static \fBMat4\fP \fBScale\fP (float x, float y, float z)"
.br
.ti -1c
.RI "static \fBMat4\fP \fBRotateX\fP (float radians)"
.br
.ti -1c
.RI "static \fBMat4\fP \fBRotateY\fP (float radians)"
.br
.ti -1c
.RI "static \fBMat4\fP \fBRotateZ\fP (float radians)"
.br
.ti -1c
.RI "static \fBMat4\fP \fBGetTransform\fP (float trans_x, float trans_y, float trans_z, float scale_x, float scale_y, float scale_Z, float rotateX, float rotateY, float rotateZ)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBm\fP [16]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Aguados Engine from the source code\&.
