.TH "Renderer" 3 "Aguados Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Renderer \- Manages the rendering pipeline for the engine, including lights, shadows, and scene geometry\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Renderer\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRenderer\fP (\fBEngine\fP &e, \fBWindow\fP &w)"
.br
.RI "Constructor for \fBRenderer\fP class\&. Takes references to the \fBEngine\fP and \fBWindow\fP objects for interaction\&. "
.ti -1c
.RI "\fB~Renderer\fP ()"
.br
.RI "Destructor for \fBRenderer\fP class\&. Performs any necessary cleanup for the rendering resources\&. "
.ti -1c
.RI "void \fBrenderLights\fP ()"
.br
.RI "Ads to rendering all lights in the scene\&. This function sets up shader light uniforms\&. "
.ti -1c
.RI "void \fBCalculateShadowsMatrix\fP ()"
.br
.RI "Calculates the shadow matrices for all lights with shadows enabled\&. This function involves using the light position and direction to calculate the projection and view matrices for shadow mapping\&. "
.ti -1c
.RI "void \fBrender\fP ()"
.br
.RI "Renders the entire scene\&. This function involves setting up shader uniforms, drawing scene geometry, and potentially post-processing effects\&. "
.ti -1c
.RI "void \fBrenderShadowMap\fP (unsigned int program)"
.br
.RI "Renders the shadow map for a specific shader program\&. "
.ti -1c
.RI "glm::mat4 \fBConfigureShadowMatrix\fP (float near, float far, \fBVec3\fP pos, \fBVec3\fP direction)"
.br
.RI "Configures the shadow matrix based on near and far planes, light position, and direction\&. "
.in -1c
.SH "Detailed Description"
.PP 
Manages the rendering pipeline for the engine, including lights, shadows, and scene geometry\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Renderer::Renderer (\fBEngine\fP & e, \fBWindow\fP & w)"

.PP
Constructor for \fBRenderer\fP class\&. Takes references to the \fBEngine\fP and \fBWindow\fP objects for interaction\&. 
.PP
\fBParameters\fP
.RS 4
\fIe\fP Reference to the \fBEngine\fP object\&. 
.br
\fIw\fP Reference to the \fBWindow\fP object\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "glm::mat4 Renderer::ConfigureShadowMatrix (float near, float far, \fBVec3\fP pos, \fBVec3\fP direction)"

.PP
Configures the shadow matrix based on near and far planes, light position, and direction\&. 
.PP
\fBParameters\fP
.RS 4
\fInear\fP The near plane distance for the shadow frustum\&. 
.br
\fIfar\fP The far plane distance for the shadow frustum\&. 
.br
\fIpos\fP The position of the light source\&. 
.br
\fIdirection\fP The direction of the light\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The calculated shadow matrix\&. 
.RE
.PP

.SS "void Renderer::renderShadowMap (unsigned int program)"

.PP
Renders the shadow map for a specific shader program\&. 
.PP
\fBParameters\fP
.RS 4
\fIprogram\fP The shader program to use for rendering the shadow map\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Aguados Engine from the source code\&.
