.TH "RIFF_Header" 3 "Aguados Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RIFF_Header
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBchunkID\fP [4]"
.br
.ti -1c
.RI "long \fBchunkSize\fP"
.br
.ti -1c
.RI "char \fBformat\fP [4]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Aguados Engine from the source code\&.
