.TH "ShaderLoader" 3 "Aguados Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ShaderLoader \- Shader Loader
.PP
 \- This file defines functions for loading and compiling shader programs\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
This file defines functions for loading and compiling shader programs\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Aguados Engine from the source code\&.
