.TH "SoundSource" 3 "Aguados Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoundSource
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSoundSource\fP (std::string name, ALfloat pos[3], ALfloat speed[3], float gain=1\&.0f, float pitch=1\&.0f)"
.br
.ti -1c
.RI "\fBSoundSource\fP (const \fBSoundSource\fP &other)"
.br
.ti -1c
.RI "\fBSoundSource\fP (\fBSoundSource\fP &other)"
.br
.ti -1c
.RI "\fBSoundSource\fP (\fBSoundSource\fP &&other)"
.br
.ti -1c
.RI "\fBSoundSource\fP & \fBoperator=\fP (const \fBSoundSource\fP &o)"
.br
.ti -1c
.RI "void \fBsetLoop\fP (bool state)"
.br
.ti -1c
.RI "void \fBsetPos\fP (ALfloat pos[3])"
.br
.ti -1c
.RI "ALfloat * \fBgetPos\fP ()"
.br
.ti -1c
.RI "void \fBsetVelocity\fP (ALfloat speed[3])"
.br
.ti -1c
.RI "ALfloat * \fBgetVelocity\fP ()"
.br
.ti -1c
.RI "void \fBupdatePos\fP (ALfloat pos[3])"
.br
.ti -1c
.RI "void \fBupdateGain\fP (float gain)"
.br
.ti -1c
.RI "void \fBupdatePitch\fP (float pitch)"
.br
.ti -1c
.RI "void \fBsetGain\fP (float gain)"
.br
.ti -1c
.RI "void \fBsetPitch\fP (float pitch)"
.br
.ti -1c
.RI "float \fBGain\fP ()"
.br
.ti -1c
.RI "float \fBPitch\fP ()"
.br
.ti -1c
.RI "bool \fBLoop\fP ()"
.br
.ti -1c
.RI "bool \fBaddSound\fP (\fBSoundBuffer\fP *b)"
.br
.ti -1c
.RI "void \fBunbindSound\fP ()"
.br
.ti -1c
.RI "bool \fBisPlaying\fP ()"
.br
.ti -1c
.RI "void \fBPlay\fP ()"
.br
.ti -1c
.RI "void \fBStop\fP ()"
.br
.ti -1c
.RI "std::string \fBName\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBdestructible_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Aguados Engine from the source code\&.
