.TH "Texture" 3 "Aguados Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Texture \- This class represents a texture object used for rendering\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <texture\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTexture\fP (TextureTarget target, TextureFormat format, TextureType type)"
.br
.ti -1c
.RI "\fB~Texture\fP ()"
.br
.ti -1c
.RI "unsigned \fBLoadTexture\fP (const char *path)"
.br
.ti -1c
.RI "unsigned \fBLoadTexture\fP (int w, int h)"
.br
.ti -1c
.RI "void \fBset_wrap_s\fP (TextureWrap param)"
.br
.ti -1c
.RI "void \fBset_wrap_t\fP (TextureWrap param)"
.br
.ti -1c
.RI "void \fBset_min_filter\fP (TextureFiltering param)"
.br
.ti -1c
.RI "void \fBset_mag_filter\fP (TextureFiltering param)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class represents a texture object used for rendering\&. 

The \fBTexture\fP class provides functionality to load and manage textures for use in rendering pipelines\&. It allows loading textures from files or creating them in memory, and setting various texture parameters like wrapping mode and filtering\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Texture::Texture (TextureTarget target, TextureFormat format, TextureType type)"
Constructor for the \fBTexture\fP class\&.
.PP
Initializes a \fBTexture\fP object with the specified target, format, and type\&.
.PP
\fBParameters\fP
.RS 4
\fItarget\fP The target of the texture\&. 
.br
\fIformat\fP The format of the texture data\&. 
.br
\fItype\fP The type of the texture data\&. 
.RE
.PP

.SS "Texture::~Texture ()"
Destructor for the \fBTexture\fP class\&.
.PP
Releases resources associated with the texture object\&. 
.SH "Member Function Documentation"
.PP 
.SS "unsigned Texture::LoadTexture (const char * path)"
Loads a texture from a file path\&.
.PP
Loads image data from the specified file path and creates a texture object\&.
.PP
\fBParameters\fP
.RS 4
\fIpath\fP The path to the image file\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The ID of the loaded texture, or 0 if loading failed\&. 
.RE
.PP

.SS "unsigned Texture::LoadTexture (int w, int h)"
Loads a texture in memory\&.
.PP
Creates a texture object with the specified width, height, and format\&. The caller is responsible for providing the pixel data\&.
.PP
\fBParameters\fP
.RS 4
\fIw\fP Width of the texture in pixels\&. 
.br
\fIh\fP Height of the texture in pixels\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The ID of the loaded texture, or 0 if creation failed\&. 
.RE
.PP

.SS "void Texture::set_mag_filter (TextureFiltering param)"
Sets the magnification filter for the texture\&.
.PP
The magnification filter determines how the texture is sampled when it's being magnified\&.
.PP
\fBParameters\fP
.RS 4
\fIparam\fP The magnification filter to use\&. 
.RE
.PP

.SS "void Texture::set_min_filter (TextureFiltering param)"
Sets the minification filter for the texture\&.
.PP
The minification filter determines how the texture is sampled when it's being shrunk\&.
.PP
\fBParameters\fP
.RS 4
\fIparam\fP The minification filter to use\&. 
.RE
.PP

.SS "void Texture::set_wrap_s (TextureWrap param)"
Sets the wrap mode for the S coordinate of the texture\&.
.PP
The wrap mode determines how texture coordinates outside the [0, 1] range are handled\&.
.PP
\fBParameters\fP
.RS 4
\fIparam\fP The wrap mode to use\&. 
.RE
.PP

.SS "void Texture::set_wrap_t (TextureWrap param)"
Sets the wrap mode for the T coordinate of the texture\&.
.PP
The wrap mode determines how texture coordinates outside the [0, 1] range are handled\&.
.PP
\fBParameters\fP
.RS 4
\fIparam\fP The wrap mode to use\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Aguados Engine from the source code\&.
