.TH "Vec2" 3 "Aguados Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vec2
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVec2\fP (float x, float y)"
.br
.ti -1c
.RI "\fBVec2\fP (const \fBVec2\fP &copy)"
.br
.ti -1c
.RI "\fBVec2\fP \fBoperator+\fP (const \fBVec2\fP &other) const"
.br
.ti -1c
.RI "\fBVec2\fP \fBoperator+\fP (float value)"
.br
.ti -1c
.RI "\fBVec2\fP & \fBoperator+=\fP (const \fBVec2\fP &other)"
.br
.ti -1c
.RI "\fBVec2\fP & \fBoperator+=\fP (float value)"
.br
.ti -1c
.RI "\fBVec2\fP \fBoperator\-\fP (const \fBVec2\fP &other) const"
.br
.ti -1c
.RI "\fBVec2\fP \fBoperator\-\fP (float value) const"
.br
.ti -1c
.RI "\fBVec2\fP & \fBoperator\-\fP ()"
.br
.ti -1c
.RI "\fBVec2\fP & \fBoperator\-=\fP (const \fBVec2\fP &other)"
.br
.ti -1c
.RI "\fBVec2\fP & \fBoperator\-=\fP (float value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBVec2\fP &other) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBVec2\fP &other) const"
.br
.ti -1c
.RI "void \fBoperator=\fP (const \fBVec2\fP &other)"
.br
.ti -1c
.RI "void \fBoperator=\fP (float value)"
.br
.ti -1c
.RI "\fBVec2\fP \fBoperator*\fP (float value) const"
.br
.ti -1c
.RI "\fBVec2\fP & \fBoperator*=\fP (float value)"
.br
.ti -1c
.RI "\fBVec2\fP \fBoperator/\fP (float value) const"
.br
.ti -1c
.RI "\fBVec2\fP & \fBoperator/=\fP (float value)"
.br
.ti -1c
.RI "float \fBMagnitude\fP () const"
.br
.ti -1c
.RI "void \fBNormalize\fP ()"
.br
.ti -1c
.RI "\fBVec2\fP \fBNormalized\fP () const"
.br
.ti -1c
.RI "void \fBScale\fP (const \fBVec2\fP scale)"
.br
.ti -1c
.RI "float \fBSqrMagnitude\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static float \fBDistance\fP (const \fBVec2\fP a, const \fBVec2\fP b)"
.br
.ti -1c
.RI "static float \fBDotProduct\fP (\fBVec2\fP a, \fBVec2\fP b)"
.br
.ti -1c
.RI "static \fBVec2\fP \fBLerp\fP (const \fBVec2\fP a, const \fBVec2\fP b, float t)"
.br
.ti -1c
.RI "static \fBVec2\fP \fBLerpUnclamped\fP (const \fBVec2\fP a, const \fBVec2\fP b, float t)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const \fBVec2\fP \fBup\fP"
.br
.ti -1c
.RI "static const \fBVec2\fP \fBdown\fP"
.br
.ti -1c
.RI "static const \fBVec2\fP \fBright\fP"
.br
.ti -1c
.RI "static const \fBVec2\fP \fBleft\fP"
.br
.ti -1c
.RI "static const \fBVec2\fP \fBzero\fP"
.br
.ti -1c
.RI "static const \fBVec2\fP \fBone\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Aguados Engine from the source code\&.
