.TH "Vec3" 3 "Aguados Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vec3
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVec3\fP (float value)"
.br
.ti -1c
.RI "\fBVec3\fP (float x, float y, float z)"
.br
.ti -1c
.RI "\fBVec3\fP (float *values_array)"
.br
.ti -1c
.RI "\fBVec3\fP (const float *values_array)"
.br
.ti -1c
.RI "\fBVec3\fP (const \fBVec3\fP &other)"
.br
.ti -1c
.RI "\fBVec3\fP \fBoperator+\fP (const \fBVec3\fP &other) const"
.br
.ti -1c
.RI "\fBVec3\fP \fBoperator+\fP (float value) const"
.br
.ti -1c
.RI "\fBVec3\fP & \fBoperator+=\fP (const \fBVec3\fP &other)"
.br
.ti -1c
.RI "\fBVec3\fP & \fBoperator+=\fP (float value)"
.br
.ti -1c
.RI "\fBVec3\fP \fBoperator\-\fP (const \fBVec3\fP &other) const"
.br
.ti -1c
.RI "\fBVec3\fP \fBoperator\-\fP (float value) const"
.br
.ti -1c
.RI "\fBVec3\fP & \fBoperator\-=\fP (const \fBVec3\fP &other)"
.br
.ti -1c
.RI "\fBVec3\fP & \fBoperator\-=\fP (float value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBVec3\fP &other) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBVec3\fP &other) const"
.br
.ti -1c
.RI "void \fBoperator=\fP (const \fBVec3\fP &other)"
.br
.ti -1c
.RI "void \fBoperator=\fP (float value)"
.br
.ti -1c
.RI "void \fBoperator=\fP (const float *value)"
.br
.ti -1c
.RI "\fBVec3\fP \fBoperator*\fP (float value) const"
.br
.ti -1c
.RI "\fBVec3\fP & \fBoperator*=\fP (float value)"
.br
.ti -1c
.RI "\fBVec3\fP \fBoperator/\fP (float value) const"
.br
.ti -1c
.RI "\fBVec3\fP & \fBoperator/=\fP (float value)"
.br
.ti -1c
.RI "float \fBMagnitude\fP () const"
.br
.ti -1c
.RI "\fBVec3\fP \fBNormalized\fP () const"
.br
.ti -1c
.RI "void \fBNormalize\fP ()"
.br
.ti -1c
.RI "float \fBSqrMagnitude\fP () const"
.br
.ti -1c
.RI "void \fBScale\fP (const \fBVec3\fP &other)"
.br
.ti -1c
.RI "\fBVec3\fP \fBCapValues\fP (float cap)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBVec3\fP \fBLerp\fP (const \fBVec3\fP &a, const \fBVec3\fP &b, float t)"
.br
.ti -1c
.RI "static \fBVec3\fP \fBLerpUnclamped\fP (const \fBVec3\fP &a, const \fBVec3\fP &b, float t)"
.br
.ti -1c
.RI "static float \fBDotProduct\fP (const \fBVec3\fP &a, const \fBVec3\fP &b)"
.br
.ti -1c
.RI "static float \fBAngle\fP (const \fBVec3\fP &a, const \fBVec3\fP &b)"
.br
.ti -1c
.RI "static \fBVec3\fP \fBCrossProduct\fP (const \fBVec3\fP &a, const \fBVec3\fP &b)"
.br
.ti -1c
.RI "static float \fBDistance\fP (const \fBVec3\fP &a, const \fBVec3\fP &b)"
.br
.ti -1c
.RI "static \fBVec3\fP \fBReflect\fP (const \fBVec3\fP &direction, const \fBVec3\fP &normal)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBz\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const \fBVec3\fP \fBup\fP"
.br
.ti -1c
.RI "static const \fBVec3\fP \fBdown\fP"
.br
.ti -1c
.RI "static const \fBVec3\fP \fBright\fP"
.br
.ti -1c
.RI "static const \fBVec3\fP \fBleft\fP"
.br
.ti -1c
.RI "static const \fBVec3\fP \fBforward\fP"
.br
.ti -1c
.RI "static const \fBVec3\fP \fBback\fP"
.br
.ti -1c
.RI "static const \fBVec3\fP \fBzero\fP"
.br
.ti -1c
.RI "static const \fBVec3\fP \fBunit\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Aguados Engine from the source code\&.
