.TH "VertexBuffer" 3 "Aguados Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VertexBuffer \- This class represents a vertex buffer object (VBO) in OpenGL\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <buffer\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~VertexBuffer\fP ()"
.br
.ti -1c
.RI "void \fBbind\fP () const"
.br
.ti -1c
.RI "void \fBunbind\fP () const"
.br
.ti -1c
.RI "unsigned \fBget\fP () const"
.br
.ti -1c
.RI "unsigned \fBgetCount\fP () const"
.br
.ti -1c
.RI "void \fBuploadFloatAttribute\fP (unsigned int id, int size, int stride, void *offset)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBResourceManager\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class represents a vertex buffer object (VBO) in OpenGL\&. 

The \fBVertexBuffer\fP class encapsulates the creation, binding, and data upload for a vertex buffer object (VBO) in OpenGL\&. It's primarily used by the \fBResourceManager\fP\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "VertexBuffer::~VertexBuffer ()"
Destructor for the \fBVertexBuffer\fP class\&.
.PP
Releases the underlying OpenGL vertex buffer object\&. 
.SH "Member Function Documentation"
.PP 
.SS "void VertexBuffer::bind () const"
Binds the vertex buffer object for use in rendering or update values\&. 
.SS "unsigned VertexBuffer::get () const"
Retrieves the handle of the underlying OpenGL vertex buffer object\&.
.PP
\fBReturns\fP
.RS 4
The unsigned integer handle representing the VBO\&. 
.RE
.PP

.SS "unsigned VertexBuffer::getCount () const"
Retrieves the number of vertices stored in the vertex buffer\&.
.PP
\fBReturns\fP
.RS 4
The count of vertices in the VBO\&. 
.RE
.PP

.SS "void VertexBuffer::unbind () const"
Unbinds the vertex buffer object, disabling its use in rendering\&. 
.SS "void VertexBuffer::uploadFloatAttribute (unsigned int id, int size, int stride, void * offset)"
Uploads float attribute data to the vertex buffer\&.
.PP
This method uploads a specific attribute to the vertex buffer, such as position, color, or texture coordinates\&.
.PP
\fBParameters\fP
.RS 4
\fIid\fP The location of the attribute in the vertex shader\&. 
.br
\fIsize\fP The number of components for the attribute\&. 
.br
\fIstride\fP The byte offset between consecutive vertices in the buffer\&. 
.br
\fIoffset\fP The byte offset within each vertex for the specific attribute\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Aguados Engine from the source code\&.
