.TH "WAVE_Format" 3 "Aguados Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WAVE_Format
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBsubChunkID\fP [4]"
.br
.ti -1c
.RI "long \fBsubChunkSize\fP"
.br
.ti -1c
.RI "short \fBaudioFormat\fP"
.br
.ti -1c
.RI "short \fBnumChannels\fP"
.br
.ti -1c
.RI "long \fBsampleRate\fP"
.br
.ti -1c
.RI "long \fBbyteRate\fP"
.br
.ti -1c
.RI "short \fBblockAlign\fP"
.br
.ti -1c
.RI "short \fBbitsPerSample\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Aguados Engine from the source code\&.
